export const sampleUsers = [
  { id: '1', name: 'David Gunn', initials: 'DG', pin: '3034', role: 'SURGEON' as const },
  { id: '2', name: 'Dr David Sharp', initials: 'DS', pin: '1234', role: 'SURGEON' as const },
  { id: '3', name: 'Anna-Louise Munro', initials: 'ALM', pin: '5678', role: 'SURGEON' as const },
  { id: '4', name: 'Kerry Lentini', initials: 'KLE', pin: '1111', role: 'NURSE' as const },
  { id: '5', name: 'Emma Layt', initials: 'ELT', pin: '2222', role: 'ANAESTHETIST' as const },
  { id: '6', name: 'Monica Roberts', initials: 'MOR', pin: '3333', role: 'NURSE' as const },
  { id: '7', name: 'Gary Cadwallender', initials: 'GCA', pin: '4444', role: 'NURSE' as const },
]

export const samplePatients = [
  {
    id: '1',
    mrn: '0019586',
    firstName: 'Sonya',
    lastName: 'GODWIN',
    title: 'Ms',
    dob: new Date('1981-10-30'),
    sex: 'Female',
    weight: 58.4,
    height: 166,
    address: '71 Glen Innes Road',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: 'Neither Aboriginal nor Torres.',
    allergies: 'No Allergies (NIL)',
    comorbidities: null,
  },
  {
    id: '2',
    mrn: '0019507',
    firstName: 'Simon',
    lastName: 'COOKE',
    title: 'Mr',
    dob: new Date('1977-12-08'),
    sex: 'Male',
    weight: 85,
    height: 178,
    address: '15 Marsh Street',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: 'Neither Aboriginal nor Torres.',
    allergies: null,
    comorbidities: null,
  },
  {
    id: '3',
    mrn: '0019552',
    firstName: 'Warren',
    lastName: 'STARKEY',
    title: 'Mr',
    dob: new Date('1951-05-31'),
    sex: 'Male',
    weight: 92,
    height: 175,
    address: '8 Oak Street',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: null,
    allergies: 'ASPIRIN, FISH OIL',
    comorbidities: 'Blood thinner',
  },
  {
    id: '4',
    mrn: '0017343',
    firstName: 'Donna',
    lastName: 'BRYDEN',
    title: 'Mrs',
    dob: new Date('1953-03-08'),
    sex: 'Female',
    weight: 70,
    height: 162,
    address: '22 Elm Avenue',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: null,
    allergies: null,
    comorbidities: null,
  },
  {
    id: '5',
    mrn: '0019513',
    firstName: 'Caroline',
    lastName: 'TURNBULL',
    title: 'Mrs',
    dob: new Date('1967-12-08'),
    sex: 'Female',
    weight: 65,
    height: 170,
    address: '45 Rose Lane',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: null,
    allergies: null,
    comorbidities: null,
  },
  {
    id: '6',
    mrn: '0019506',
    firstName: 'Martin phillip',
    lastName: 'BOYD',
    title: 'Mr',
    dob: new Date('1966-09-22'),
    sex: 'Male',
    weight: 88,
    height: 180,
    address: '10 Birch Road',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: null,
    allergies: null,
    comorbidities: null,
  },
  {
    id: '7',
    mrn: '0011479',
    firstName: 'Carl',
    lastName: 'PLANTING',
    title: 'Mr',
    dob: new Date('1943-11-29'),
    sex: 'Male',
    weight: 78,
    height: 172,
    address: '33 Cedar Court',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: null,
    allergies: 'ASPIRIN',
    comorbidities: 'Blood thinner',
  },
  {
    id: '8',
    mrn: '0019508',
    firstName: 'Lynn',
    lastName: 'KINCADE',
    title: 'Ms',
    dob: new Date('1953-11-04'),
    sex: 'Female',
    weight: 62,
    height: 160,
    address: '5 Pine Street',
    suburb: 'ARMIDALE',
    state: 'NSW',
    postcode: '2350',
    atsiStatus: null,
    allergies: null,
    comorbidities: null,
  },
]

export const sampleAdmissions = [
  {
    id: '1',
    patientId: '1',
    date: new Date('2026-03-19'),
    time: '06:41',
    status: 'RECOVERY_1' as const,
    operationNotes: 'ABDOMINOPLASTY AND MASTOPEXY WITH BILATERAL BREAST AUGMENTATION #COSMETIC',
    location: 'Theatre 1',
    surgeonId: '2',
    anaesthetistId: '5',
    procedureStartTime: '08:01',
    covidStatus: 'Not Asked Yet',
    lastFood: new Date('2026-03-18T19:30:00'),
    lastFluid: new Date('2026-03-18T21:00:00'),
  },
  {
    id: '2',
    patientId: '2',
    date: new Date('2026-03-19'),
    time: '07:00',
    status: 'DISCHARGED' as const,
    operationNotes: 'RIGHT CATARACT Alcon PanOptix Pro Toric PXYAT2 +21.50/+1.00 x 144EQR',
    location: 'Theatre 2',
    surgeonId: '1',
    anaesthetistId: '5',
    procedureStartTime: '09:15',
    covidStatus: 'Not Asked Yet',
    lastFood: null,
    lastFluid: null,
  },
  {
    id: '3',
    patientId: '3',
    date: new Date('2026-03-19'),
    time: '07:15',
    status: 'DISCHARGED' as const,
    operationNotes: 'RIGHT LOWER LID ECTROPIAN REPAIR BLOOD THINNER ASPIRIN/FISH OIL - HAS CEASED SURGERY CONNECT',
    location: 'Theatre 1',
    surgeonId: '3',
    anaesthetistId: null,
    procedureStartTime: '10:00',
    covidStatus: null,
    lastFood: null,
    lastFluid: null,
  },
  {
    id: '4',
    patientId: '4',
    date: new Date('2026-03-19'),
    time: '07:30',
    status: 'DISCHARGED' as const,
    operationNotes: 'RIGHT CATARACT Alcon Clareon Toric CNA0T2 +22.00/+1.00 x 162',
    location: 'Theatre 2',
    surgeonId: '1',
    anaesthetistId: null,
    procedureStartTime: '10:30',
    covidStatus: null,
    lastFood: null,
    lastFluid: null,
  },
  {
    id: '5',
    patientId: '5',
    date: new Date('2026-03-19'),
    time: null,
    status: 'BOOKED' as const,
    operationNotes: 'FOCUS - RIGHT CATARACT Alcon PanOptix Pro PXYAT0 +21.50',
    location: 'Theatre 2',
    surgeonId: '1',
    anaesthetistId: null,
    procedureStartTime: null,
    covidStatus: null,
    lastFood: null,
    lastFluid: null,
  },
  {
    id: '6',
    patientId: '6',
    date: new Date('2026-03-19'),
    time: '08:00',
    status: 'DISCHARGED' as const,
    operationNotes: 'RIGHT CATARACT Alcon PanOptix Pro Toric PXYAT3 +20.50/+1.50 x 6EQR',
    location: 'Theatre 2',
    surgeonId: '1',
    anaesthetistId: null,
    procedureStartTime: '11:00',
    covidStatus: null,
    lastFood: null,
    lastFluid: null,
  },
  {
    id: '7',
    patientId: '7',
    date: new Date('2026-03-19'),
    time: '08:30',
    status: 'DISCHARGED' as const,
    operationNotes: 'BILATERAL LOWER LID ECTRIOPIAN REPAIR AND LOWER BLEPHAROPLASTY BLOOD THINNER: ASPIRIN',
    location: 'Theatre 1',
    surgeonId: '3',
    anaesthetistId: null,
    procedureStartTime: '11:30',
    covidStatus: null,
    lastFood: null,
    lastFluid: null,
  },
  {
    id: '8',
    patientId: '8',
    date: new Date('2026-03-19'),
    time: '09:00',
    status: 'DISCHARGED' as const,
    operationNotes: 'RIGHT CATARACT + HYDRUS J&J Puresee Toric +19.50 DET150 x 161EQR',
    location: 'Theatre 2',
    surgeonId: '1',
    anaesthetistId: null,
    procedureStartTime: '12:00',
    covidStatus: null,
    lastFood: null,
    lastFluid: null,
  },
]

export const sampleObservations = [
  { id: '1', admissionId: '1', time: new Date('2026-03-19T06:45:00'), rr: 14, spo2: 100, hr: 86, bpSystolic: 117, bpDiastolic: 64, temp: 36.6, userId: '4' },
  { id: '2', admissionId: '1', time: new Date('2026-03-19T07:00:00'), rr: 15, spo2: 99, hr: 84, bpSystolic: 120, bpDiastolic: 68, temp: 36.5, userId: '4' },
  { id: '3', admissionId: '1', time: new Date('2026-03-19T08:30:00'), rr: 13, spo2: 100, hr: 80, bpSystolic: 115, bpDiastolic: 62, temp: 36.4, userId: '6' },
  { id: '4', admissionId: '1', time: new Date('2026-03-19T09:30:00'), rr: 14, spo2: 99, hr: 78, bpSystolic: 118, bpDiastolic: 65, temp: 36.5, userId: '6' },
  { id: '5', admissionId: '1', time: new Date('2026-03-19T10:30:00'), rr: 14, spo2: 100, hr: 82, bpSystolic: 122, bpDiastolic: 70, temp: 36.6, userId: '7' },
  { id: '6', admissionId: '1', time: new Date('2026-03-19T11:00:00'), rr: 13, spo2: 98, hr: 100, bpSystolic: 105, bpDiastolic: 45, temp: 36.3, userId: '7' },
  { id: '7', admissionId: '1', time: new Date('2026-03-19T11:15:00'), rr: 14, spo2: 99, hr: 98, bpSystolic: 108, bpDiastolic: 48, temp: 36.4, userId: '7' },
  { id: '8', admissionId: '1', time: new Date('2026-03-19T11:30:00'), rr: 15, spo2: 99, hr: 95, bpSystolic: 110, bpDiastolic: 50, temp: 36.5, userId: '7' },
  { id: '9', admissionId: '1', time: new Date('2026-03-19T11:45:00'), rr: 14, spo2: 100, hr: 92, bpSystolic: 115, bpDiastolic: 55, temp: 36.5, userId: '7' },
  { id: '10', admissionId: '1', time: new Date('2026-03-19T12:00:00'), rr: 16, spo2: 100, hr: 88, bpSystolic: 120, bpDiastolic: 60, temp: 36.6, userId: '7' },
]

export const sampleNotes = [
  { id: '1', admissionId: '1', dateTime: new Date('2026-03-19T06:54:00'), content: 'Ted stocking given and applied by patient. Patient stated currently on period. Sanitary pad insitu but will change to tampon if required. Anaesthetic team notified.', userId: '4' },
  { id: '2', admissionId: '1', dateTime: new Date('2026-03-19T11:49:00'), content: 'Patient arrived in PACU at 1130, unresponsive with LMA insitu. Spontaneous resps, O2 6L/min. Obs as charted. Anaesthetist and Scrub nurse handover completed. Dressings checked, nil ooze. Drainage in situ.', userId: '7' },
]

export const sampleHandovers = [
  { id: '1', admissionId: '1', stage: 'ADMISSION' as const, fromUserId: '4', toUserId: null, time: null },
  { id: '2', admissionId: '1', stage: 'ANAESTHESIA' as const, fromUserId: '5', toUserId: null, time: '00:00' },
  { id: '3', admissionId: '1', stage: 'PROCEDURE' as const, fromUserId: '6', toUserId: '7', time: '11:45' },
  { id: '4', admissionId: '1', stage: 'RECOVERY_1' as const, fromUserId: '7', toUserId: null, time: null },
]

// Helper to find data
export function findUser(id: string) {
  return sampleUsers.find(u => u.id === id)
}

export function findPatient(id: string) {
  return samplePatients.find(p => p.id === id)
}

export function findAdmission(id: string) {
  return sampleAdmissions.find(a => a.id === id)
}

export function getAdmissionsByDate(dateStr: string) {
  return sampleAdmissions.filter(a => {
    const admDate = a.date.toISOString().split('T')[0]
    return admDate === dateStr
  })
}

export function getObservationsForAdmission(admissionId: string) {
  return sampleObservations.filter(o => o.admissionId === admissionId)
}

export function getNotesForAdmission(admissionId: string) {
  return sampleNotes.filter(n => n.admissionId === admissionId)
}

export function getHandoversForAdmission(admissionId: string) {
  return sampleHandovers.filter(h => h.admissionId === admissionId)
}
